#!/bin/bash

# cubify by eri
# USAGE: cubify [in] [out]
# you should probably use a transparent image format
# currently doesn't work with gifs but i might add that later

TMP=$(mktemp -d)     #make temporary directory

convert $1 -resize 260x301! -alpha set -background none -shear 0x30  -rotate -60 -trim   "$TMP"/top.png     #make the top face
convert $1 -resize 260x301! -alpha set -background none -shear 0x30  -level 20%,100%,0.9 "$TMP"/left.png    #make the left face
convert $1 -resize 260x301! -alpha set -background none -shear 0x-30 -level 30%,100%,0.8 "$TMP"/right.png   #make the right face

convert "$TMP"/left.png "$TMP"/right.png +append \( "$TMP"/top.png -repage +0-149 \) -background none -layers merge +repage $2   #combine faces

rm -r "$TMP"   #remove temporary directory