#!/bin/bash

#cubify-gui by eri
#a gui-ish thing for cubify

IN=$(zenity --file-selection --title=input file)    #ask for file to cubify

TIME=$(date "+%Y.%m.%d-%H.%M.%S")   #get time for timestamp

cubify "$IN" ~/Pictures/cube_"$TIME".png    #call cubify

xdg-open ~/Pictures/cube_"$TIME".png   #open image