#!/bin/bash

#memeify-gui by eri
#a gui-ish thing for memeify

IN=$(zenity --file-selection --title=input file)    #ask for file to memeify
CAP=$(zenity --forms --title=memeify --text="caption" --add-entry="top text" --add-entry="bottom text (optional)")  #ask for caption

IFS='|' 
read -a CAP <<<"$CAP"   #turn zenity output into an array
IFS=' '

TIME=$(date "+%Y.%m.%d-%H.%M.%S")   #get time for timestamp

memeify "$IN" ~/Pictures/meme_"$TIME".png "${CAP[0]}" "${CAP[1]}"   #call memeify

xdg-open ~/Pictures/meme_"$TIME".png   #open image