#!/bin/bash

#memeify-neue-gui by eri
#a gui-ish thing for memeify-neue

IN=$(zenity --file-selection --title=input file)    #ask for file to memeify
CAP=$(zenity --forms --title=memeify --text="caption" --add-entry="text")  #ask for caption

TIME=$(date "+%Y.%m.%d-%H.%M.%S")   #get time for timestamp

memeify-neue "$IN" ~/Pictures/meme_"$TIME".png "$CAP" #call memeify-neue

xdg-open ~/Pictures/meme_"$TIME".png   #open image